#!/bin/sh

####################################################
# Tux2live Project
#
# Name: 
#
# Description:
#
# Author: Ceasar Sun <ceasar_at_nchc_org_tw>
####################################################
[ -f "/etc/tux2live.conf" ] && . /etc/tux2live.conf

_description="Stop anacron ..."

# Main
if [ ! -e /etc/debian_version -a ! -e /etc/SuSE-release ]; then
# scripts run in rh-like distro
	echo "$_description"

	if [ -x /etc/init.d/crond ]; then
	    for f in /etc/rc?.d/S??crond; do
	        mv ${f} ${f%/*}/K00crond
	    done
	fi
fi
